flowchart TD
    A["03-I-00-00-00<br/>general"]
    B01["03-I-00-01-00<br/>purpose_scope"]
    B02["03-I-00-02-00<br/>reference_baseline"]
    B03["03-I-00-03-00<br/>operational_concept"]
    B04["03-I-00-04-00<br/>site_facility_framework"]
    B05["03-I-00-05-00<br/>common_utilities_services"]
    B06["03-I-00-06-00<br/>safety_emergency_framework"]
    B07["03-I-00-07-00<br/>security_access_control"]
    B08["03-I-00-08-00<br/>data_digital_interoperability"]
    B09["03-I-00-09-00<br/>human_factors_documentation"]
    B10["03-I-00-10-00<br/>maintenance_supportability"]
    B11["03-I-00-11-00<br/>environmental_sustainability"]
    B12["03-I-00-12-00<br/>compliance_certification"]
    B13["03-I-00-13-00<br/>configuration_governance_performance"]

    A --> B01
    A --> B02
    A --> B03
    A --> B04
    A --> B05
    A --> B06
    A --> B07
    A --> B08
    A --> B09
    A --> B10
    A --> B11
    A --> B12
    A --> B13
